[build]
  publish = "dist/"
  command = "pnpm run build"

[build.environment]
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  NPM_FLAGS = "--platform=linux --arch=x64"

[[plugins]]
  package = "./netlify/plugins/prebuild-sharp"