[build]
  publish = "dist/"
  command = "cp netlify.astro.config.mjs astro.config.mjs && pnpm run build"

[build.environment]
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  NPM_FLAGS = "--platform=linux --arch=x64"