backend:
  name: git-gateway
  branch: main # Branch to update

# For production, use identity-based authentication
publish_mode: editorial_workflow
media_folder: "public/uploads" # Media will be stored in the repo under public/uploads
public_folder: "/uploads" # The src attribute for uploaded media
